// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace unitygames.leveldesign {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.IOC;
    using uFrame.MVVM;
    using uFrame.Serialization;
    using UniRx;
    
    
    public class BobPlayerControllerBase : uFrame.MVVM.Controller {
        
        private uFrame.MVVM.IViewModelManager _BobPlayerViewModelManager;
        
        [uFrame.IOC.InjectAttribute("BobPlayer")]
        public uFrame.MVVM.IViewModelManager BobPlayerViewModelManager {
            get {
                return _BobPlayerViewModelManager;
            }
            set {
                _BobPlayerViewModelManager = value;
            }
        }
        
        public IEnumerable<BobPlayerViewModel> BobPlayerViewModels {
            get {
                return BobPlayerViewModelManager.OfType<BobPlayerViewModel>();
            }
        }
        
        public override void Setup() {
            base.Setup();
            // This is called when the controller is created
        }
        
        public override void Initialize(uFrame.MVVM.ViewModel viewModel) {
            base.Initialize(viewModel);
            // This is called when a viewmodel is created
            this.InitializeBobPlayer(((BobPlayerViewModel)(viewModel)));
        }
        
        public virtual BobPlayerViewModel CreateBobPlayer() {
            return ((BobPlayerViewModel)(this.Create(Guid.NewGuid().ToString())));
        }
        
        public override uFrame.MVVM.ViewModel CreateEmpty() {
            return new BobPlayerViewModel(this.EventAggregator);
        }
        
        public virtual void InitializeBobPlayer(BobPlayerViewModel viewModel) {
            // This is called when a BobPlayerViewModel is created
            BobPlayerViewModelManager.Add(viewModel);
        }
        
        public override void DisposingViewModel(uFrame.MVVM.ViewModel viewModel) {
            base.DisposingViewModel(viewModel);
            BobPlayerViewModelManager.Remove(viewModel);
        }
    }
}
