// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace unitygames.leveldesign {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    
    
    public class GameSystemLoaderBase : uFrame.Kernel.SystemLoader {
        
        public override void Load() {
        }
    }
    
    public class CharactersSystemLoaderBase : uFrame.Kernel.SystemLoader {
        
        private BobPlayerController _BobPlayerController;
        
        [uFrame.IOC.InjectAttribute()]
        public virtual BobPlayerController BobPlayerController {
            get {
                if (_BobPlayerController==null) {
                    _BobPlayerController = Container.CreateInstance(typeof(BobPlayerController)) as BobPlayerController;;
                }
                return _BobPlayerController;
            }
            set {
                _BobPlayerController = value;
            }
        }
        
        public override void Load() {
            Container.RegisterViewModelManager<BobPlayerViewModel>(new ViewModelManager<BobPlayerViewModel>());
            Container.RegisterController<BobPlayerController>(BobPlayerController);
        }
    }
}
